// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDUWeatherPredictor.Client;

namespace RDUWeatherPredictor.Migrations
{
    [DbContext(typeof(ConsoleWeatherDbContext))]
    partial class ConsoleWeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RDUWeatherPredictor.DailyNormal", b =>
                {
                    b.Property<int>("JulianDay")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DayOfMonth");

                    b.Property<string>("Month");

                    b.Property<float>("NormalMaxTempF");

                    b.Property<float>("NormalMinTempF");

                    b.Property<float?>("NormalPrecipitation");

                    b.HasKey("JulianDay");

                    b.ToTable("DailyNormals");
                });
#pragma warning restore 612, 618
        }
    }
}
